server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource  #使用hikari连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_srb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: system

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #设置日志
  mapper-locations: classpath:/mapper/*.xml #指定mapper文件的位置